Updates

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -21,7 +21,10 @@ jobs:
           distribution: 'liberica'
 
       - name: Build with Maven
-        run: mvn clean package -D skipTests
+        run: mvn clean package -DskipTests
+
+      - name: Debug target directory
+        run: ls -la target/ || echo "target/ directory not found"
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -35,6 +38,7 @@ jobs:
       - name: Build And Push
         uses: docker/build-push-action@v6
         with:
+          context: .
           push: true
           file: Dockerfile
           tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
